- name: Install or update Git
  apt:
    name: git
    state: latest
- name: Configure Git
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - name: user.email
      value: benjamin.fischer@evolutics.info
    - name: user.name
      value: Benjamin Fischer
    - name: core.editor
      value: code --wait
- name: Install or update gitk
  apt:
    name: gitk
    state: latest
