- name: Configure keyboard layouts Neo 2 as major and US as minor
  lineinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    line: "setxkbmap -layout de,us -variant neo,"
  register: keyboard_layouts
- name: Reload profile to apply keyboard layout changes now
  shell: ". {{ ansible_env.HOME }}/.profile"
  when: keyboard_layouts.changed
