- name: Configure desktop theme # noqa 301
  command: "xfconf-query --channel {{ item.channel }}
    --property {{ item.property }}
    --create --set {{ item.set }} --type {{ item.type }}"
  with_items:
    - channel: xsettings
      property: /Net/ThemeName
      set: Numix
      type: string
    - channel: xfwm4
      property: /general/theme
      set: Numix
      type: string
