- import_tasks: legacy_cleanup.yml
- import_tasks: package_repositories.yml

- import_tasks: bash.yml
- import_tasks: direnv.yml
- import_tasks: docker.yml
- import_tasks: git.yml
- import_tasks: keyboard_layout.yml
- import_tasks: variety.yml
- import_tasks: virtualbox.yml
- import_tasks: visual_studio_code.yml

- import_tasks: package_updates.yml
- import_tasks: package_cleanup.yml
