- name: Install Git
  become: true
  apt:
    name: git
- name: Configure Git
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - name: user.email
      value: "{{ email_address }}"
    - name: user.name
      value: Benjamin Fischer
    - name: core.editor
      value: code --wait
- name: Install gitk
  become: true
  apt:
    name: gitk
