- name: Configure Bash history tracking
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^export HISTFILESIZE="
      line: "export HISTFILESIZE=200000"
    - regexp: "^export HISTSIZE="
      line: "export HISTSIZE=100000"
