- name: Configure Bash history tracking
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^HISTFILESIZE="
      line: "HISTFILESIZE=200000"
    - regexp: "^HISTSIZE="
      line: "HISTSIZE=100000"
