- name: Install Visual Studio Code
  import_role:
    name: gantsign.visual-studio-code
  vars:
    users:
      - username: "{{ ansible_user_id }}"
        visual_studio_code_extensions:
          - eamodio.gitlens
          - esbenp.prettier-vscode
          - streetsidesoftware.code-spell-checker
        visual_studio_code_settings:
          diffEditor.ignoreTrimWhitespace: false
          editor.rulers:
            - 80
- name: Configure Visual Studio Code as default for plain text files
  ini_file:
    path: "{{ ansible_env.HOME }}/.config/mimeapps.list"
    section: Default Applications
    option: text/plain
    value: code.desktop
